import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#6a7378",
        "inverse-primary": "#94ccff",
        outline: "#707881",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#9feffe",
        "on-tertiary-fixed": "#141d21",
        "inverse-on-surface": "#eff1f3",
        tertiary: "#525b60",
        "on-primary-container": "#f3f7ff",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#bfc8ce",
        "outline-variant": "#bfc7d1",
        "primary-fixed": "#cde5ff",
        "secondary-fixed-dim": "#83d3e1",
        "on-surface-variant": "#404850",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        secondary: "#006875",
        "on-secondary-fixed": "#001f24",
        "primary-fixed-dim": "#94ccff",
        "on-primary-fixed": "#001d32",
        "tertiary-fixed": "#dbe4ea",
        "seafoam-accent": "#A3E635",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "primary-container": "#0077b6",
        "on-tertiary-fixed-variant": "#3f484d",
        "surface-tint": "#006399",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#004f59",
        primary: "#005d90",
        "secondary-container": "#9cecfb",
        "deep-ocean": "#023E8A",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#f0f9ff",
        "sand-white": "#FDFAFF",
        "on-tertiary": "#ffffff",
        background: "#f7f9fb",
        surface: "#f7f9fb",
        "inverse-surface": "#2d3133",
        "on-secondary-container": "#016d7a",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#004b74",
        "on-secondary": "#ffffff",
        "soft-slate": "#64748B",
        "surface-container": "#eceef0",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "48px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max-width": "1200px",
      },
      fontFamily: {
        "headline-md": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max-width": "1200px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
